# Generated by Django 5.0.3 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="StageOfCatch",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="TeamMember",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="IncidentDescription",
            field=models.CharField(default="wrong patient", max_length=300),
        ),
    ]
