# Generated by Django 5.0.3 on 2025-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0002_incidentreport_stageofcatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="IncidentDescription",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="Location",
            field=models.CharField(default=" ", max_length=300),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="StageOfCatch",
            field=models.CharField(blank=True, default=" ", max_length=35, null=True),
        ),
    ]
