# Generated by Django 5.0.3 on 2025-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0003_alter_incidentreport_incidentdescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="StageOfCatch",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
